package com.rapipeline.model;

public enum ErrorCategory {
    INGESTION_MISSING_DATA,
    INGESTION_UNSUPPORTED,
    INGESTION_FILE_MISSING,
    INGESTION_SYSTEM_ERROR,
    PREPROCESSING_ERROR,
    AUTOMAPPER_ERROR
}
