CREATE TABLE RA_RT_PROVIDER_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  source_nm varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
    creat_user_id VARCHAR2(10),
    last_updt_dt TIMESTAMP(6),
    last_updt_user_id VARCHAR2(10)
);

CREATE TABLE RA_RT_PROV_MARKET_LOB_MAP (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_prov_details_id Number,
  market varchar(32),
  lob varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id VARCHAR2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id VARCHAR2(10)
);

CREATE TABLE RA_RT_FILE_DETAILS_LOB (
  id Number,
  ra_file_details_id Number,
  lob varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_FILE_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_provider_details_id Number,
  orgnl_file_nm varchar(32),
  stndrdzd_file_nm varchar(32),
  source_nm varchar(32),
  market varchar(32),
  status_cd NUMBER,
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_FILE_ALT_IDS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id Number,
  alt_id varchar(32),
  alt_id_type varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_CONTACT_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  contact varchar(32),
  contact_type varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_ERROR_LOGS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  ra_sheet_details_id NUMBER,
  error_cd_details_id NUMBER,
  stage_nm varchar(32),
  error_desc varchar(1024),
  error_long_desc varchar(1024),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);



CREATE TABLE RA_RT_FILE_ALT_IDS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id Number,
  alt_id varchar(32),
  alt_id_type varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_CONTACT_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  contact varchar(32),
  contact_type varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_ERROR_LOGS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  ra_sheet_details_id NUMBER,
  error_cd_details_id NUMBER,
  stage_nm varchar(32),
  error_desc varchar(1024),
  error_long_desc varchar(1024),
  creat_dt TIMESTAMP(6),
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6),
  last_updt_user_id varchar2(10)
);




