create table RA_RT_PROVIDER_DETAILS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    source_nm varchar(32),
    is_active NUMBER(1),
    creat_dt TIMESTAMP(6) DEFAULT sysdate,
    creat_user_id VARCHAR2(10),
    last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
    last_updt_user_id VARCHAR2(10)
);

create table RA_RT_PROV_MARKET_LOB_MAP(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ra_prov_details_id Number,
    market varchar(32),
    lob varchar(32),
    is_active NUMBER(1),
    creat_dt TIMESTAMP(6) DEFAULT sysdate,
    creat_user_id VARCHAR2(10),
    last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
    last_updt_user_id VARCHAR2(10)
);

CREATE TABLE RA_RT_FILE_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_provider_details_id NUMBER,
  orgnl_file_nm varchar(64),
  stndrdzd_file_nm varchar(64),
  market varchar(32),
  status_cd NUMBER,
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_FILE_DETAILS_LOB (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id Number,
  lob varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_FILE_ALT_IDS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id Number,
  alt_id varchar(32),
  alt_id_type varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_CONTACT_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  contact varchar(32),
  contact_type varchar(32),
  is_active NUMBER(1),
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_SHEET_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  status_cd NUMBER,
  tab_nm varchar(32),
  type varchar(32),
  roster_record_cnt NUMBER,
  auto_mapped_record_cnt NUMBER,
  isf_record_cnt NUMBER,
  isf_row_cnt NUMBER,
  out_row_cnt NUMBER,
  out_record_cnt NUMBER,
  target_successful_record_cnt NUMBER,
  manual_review_record_cnt NUMBER,
  target_load_success_trnsctn_cnt NUMBER,
  isf_file_nm varchar(32),
  out_file_nm varchar(32),
  creat_dt TIMESTAMP(6) DEFAULT sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_ERROR_LOGS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_file_details_id NUMBER,
  ra_sheet_details_id NUMBER,
  error_cd_details_id NUMBER,
  stage_nm varchar(32),
  error_desc varchar(1024),
  error_long_desc varchar(1024),
  creat_dt TIMESTAMP(6) DEFAULT sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) DEFAULT sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_STATUS_CD_MSTR (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  status_cd NUMBER,
  bsns_status varchar(32),
  status_desc varchar(1024),
  stage_nm varchar(32),
  is_active NUMBER(1),
  is_cmplt_status NUMBER(1),
  is_fail_status NUMBER(1),
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) default sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RT_CONV_PROCESSING_DURATION_STATS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ra_sheet_details_id NUMBER,
  status_cd NUMBER,
  start_dt timestamp,
  cmpltn_dt timestamp,
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) default sysdate,
  last_updt_user_id varchar2(10)
);

CREATE TABLE RA_RC_FALLOUT_REPORT (
  id NUMBER,
  ra_sheet_details_id NUMBER,
  ra_row_id varchar(32),
  rule_ctgry_stage varchar(32),
  err_type varchar(32),
  err_dscrptn varchar(1024),
  trnsctn_type varchar(32),
  recommendation_action varchar(1024),
  creat_dt TIMESTAMP(6) default sysdate,
  creat_user_id varchar2(10),
  last_updt_dt TIMESTAMP(6) default sysdate,
  last_updt_user_id varchar2(10)
)
